image: Ubuntu1804 # образ для сборки
stack: node 14 # окружение
branches:
  only:
    - target # ветка git
cache: node_modules # кэширование
install:
  - npm install # команда установки зависимостей
build: off
test_script:
  - npm rum lint && npm test # скрипт сборки